<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:dbx="http://docblox-project.org/xsl/functions">

  <xsl:output indent="yes" method="html" />
  <xsl:include href="chrome.xsl" />

  <xsl:template match="/project">

    <div class="content">
        <h2>Documentation Overview</h2>

        <h3>Package</h3>

        <dl>
            <dt>Files:</dt>
            <dd><xsl:value-of select="count(/project/file)" /></dd>

            <dt>Classes:</dt>
            <dd><xsl:value-of select="count(/project/*/class)" /></dd>

            <dt>Functions</dt>
            <dd><xsl:value-of select="count(/project/*/function)" /></dd>

            <dt>Methods</dt>
            <dd><xsl:value-of select="count(/project/*//method)" /></dd>

            <dt>Constants</dt>
            <dd><xsl:value-of select="count(/project/*//constant)" /></dd>
        </dl>

        <h3>Validation</h3>
        <dl>
            <dt>

                Parse Errors
            </dt>
            <dd>
                <xsl:if test="count(/project/file/parse_markers) > 0">
                    <a href="{$root}report_parse_markers.html">
                        <xsl:value-of select="count(/project/file/parse_markers)" />
                    </a>
                </xsl:if>
                <xsl:if test="count(/project/file/parse_markers) = 0">
                    <xsl:value-of select="count(/project/file/parse_markers)" />
                </xsl:if>
            </dd>
        </dl>

        <h3>Markers</h3>
        <dl>
            <xsl:for-each select="/project/marker">
                <xsl:variable name="marker" select="."/>

                <dt><xsl:value-of select="$marker" /></dt>
                <dd>
                    <xsl:if test="count(/project/file/*/tag[@name=$marker]) > 0">
                        <a href="{$root}report_markers.html">
                            <xsl:value-of select="count(/project/file/*/tag[@name=$marker])" />
                        </a>
                    </xsl:if>
                    <xsl:if test="count(/project/file/*/tag[@name=$marker]) = 0">
                        <xsl:value-of select="count(/project/file/*/tag[@name=$marker])" />
                    </xsl:if>

                </dd>

            </xsl:for-each>
        </dl>

        This documentation was generated by <a href="http://www.docblox-project.org">DocBlox <xsl:value-of select="$version" /></a>.
    </div>

  </xsl:template>
</xsl:stylesheet>